### ISSUE TITLE
More ergonomic access to signed cookies

### ISSUE THREAD

**Issue by davidpdrsn** [imbolc/tower-cookies#3]
For implementing [`axum-flash`](https://github.com/davidpdrsn/axum-flash) I needed signed cookies to make sure third parties hadn't tampered with them. I did that like so [this](https://github.com/davidpdrsn/axum-flash/blob/main/src/lib.rs#L186-L190):

- Creating a temporary `cookie::CookieJar` and a signed child jar
- Putting a cookie into it
- Reading the cookie again to get the now signed value
- Writing that to `tower_cookies::Cookies`

For reading the value I did same but in reverse.

Would be nice if `tower-cookies` provided a more ergonomic way to do this. Perhaps adding methods similar to those found on [`cookies::CookieJar`](https://docs.rs/cookie/0.15.1/cookie/struct.CookieJar.html) to create signed jars, ie `CookieJar::signed` and `CookieJar::signed_mut`.

By the way thanks for tower-cookies. Its really nice 😊

**Comment by imbolc** [comment]
Thank you, David, the nicety is actually due to @programatik29 involvement :)

I postponed integration of `cookies::SingnedJar` and `PrivateJar`, because I know very little about security. So I planned to get at least some knowledge of algos used there first. But now I doubt I'll do this in the near future. So I guess I'll just bring them here as they are in the `cookies` crate. I'll look into it this week.

**Comment by imbolc** [comment]
Hey, @davidpdrsn :) I've added `Cookies::signed()` method: https://github.com/imbolc/tower-cookies/blob/signed-cookies/src/signed.rs

But there's only `add()` and `get()` methods (`remove` can be used directly from parent). So I'm thinking maybe adding `add_signed()` and `get_signed()` methods to `Cookies` would look better. There's no performance difference, as we're still creating `SignedJar` at every call because of mutex.

So it's `cookies.signed(&key).add(my_cookie)` vs `cookies.add_signed(my_cookie, &key)`.

What do you think?

**Comment by davidpdrsn** [comment]
Having `remove` only on the parent jar is fine for [`axum-flash`](https://github.com/davidpdrsn/axum-flash/blob/main/src/incoming_flash.rs#L93).

I personally prefer `cookies.signed(&key).add(my_cookie)` since it allows you to create a signed jar and hand that off to some subsystem and be guaranteed that it only deals with signed cookies. I don't have a specific use case for that though, just a thought.

**Comment by imbolc** [comment]
That makes sense, it means it's better to have `remove` there after all. Thank you :pray:

**Comment by imbolc** [comment]
Published :)

**Comment by davidpdrsn** [comment]
Thanks! I'll get a new version of axum-flash out 😊
